
class Autogenerated {
  List<Data>? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int? id;
  String? name;
  String? description;
  String? createdAt;
  String? updatedAt;
  List<Foods>? foods;


  Data(
      {this.id,
        this.name,
        this.description,
        this.createdAt,
        this.updatedAt,
        this.foods,
        });

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    description = json['description'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];

    if (json['foods'] != null) {
      foods = <Foods>[];
      json['foods'].forEach((v) {
        foods!.add(new Foods.fromJson(v));
      });
    }

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['description'] = this.description;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;

    return data;
  }
}

class Foods {
  int? id;
  String? name;
  int? price;
  int? discountPrice;
  String? description;
  // Null ingredients;
  // Null packageItemsCount;
  // Null weight;
  // Null unit;
  bool? featured;
  bool? deliverable;
  int? restaurantId;
  int? categoryId;
  String? createdAt;
  String? updatedAt;
  List<Null>? customFields;
  bool? hasMedia; 
  Restaurants? restaurant;
  List? media;

  Foods(
      {this.id,
        this.name,
        this.price,
        this.discountPrice,
        this.description,
        // this.ingredients,
        // this.packageItemsCount,
        // this.weight,
        // this.unit,
        this.featured,
        this.deliverable,
        this.restaurantId,
        this.categoryId,
        this.createdAt,
        this.updatedAt,
        this.customFields,
        this.hasMedia ,
        this.restaurant,
this.media
        });

  Foods.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    price = json['price'];
    discountPrice = json['discount_price'];
    description = json['description'];
    // ingredients = json['ingredients'];
    // packageItemsCount = json['package_items_count'];
    // weight = json['weight'];
    // unit = json['unit'];
    featured = json['featured'];
    deliverable = json['deliverable'];
    restaurantId = json['restaurant_id'];
    categoryId = json['category_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];

    hasMedia = json['has_media'];

    restaurant = json['restaurant'] != null
        ? new Restaurants.fromJson(json['restaurant'])
        : null;
    media=json['media'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['price'] = this.price;
    data['discount_price'] = this.discountPrice;
    data['description'] = this.description;
    // data['ingredients'] = this.ingredients;
    // data['package_items_count'] = this.packageItemsCount;
    // data['weight'] = this.weight;
    // data['unit'] = this.unit;
    data['featured'] = this.featured;
    data['deliverable'] = this.deliverable;
    data['restaurant_id'] = this.restaurantId;
    data['category_id'] = this.categoryId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;

    return data;
  }
}

class Restaurants {
  int? id;
  String? name;
  int? deliveryFee;
  String? address;
  String? phone;
  int? defaultTax;
  bool? availableForDelivery;
  List<Null>? customFields;
  bool? hasMedia;
  bool? hasFaviconMedia;
  String? rate;
  int? reviewsCount;
  List? media;
  Restaurants(
      {this.id,
        this.name,
        this.deliveryFee,
        this.address,
        this.phone,
        this.defaultTax,
        this.availableForDelivery,
        this.customFields,
        this.hasMedia,
        this.hasFaviconMedia,
        this.rate,
        this.reviewsCount,this.media
        });

  Restaurants.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    deliveryFee = json['delivery_fee'];
    address = json['address'];
    phone = json['phone'];
    defaultTax = json['default_tax'];
    availableForDelivery = json['available_for_delivery'];


    hasFaviconMedia = json['has_favicon_media'];
    rate = json['rate'];
    reviewsCount = json['reviews_count'];

    media = json['media'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['delivery_fee'] = this.deliveryFee;
    data['address'] = this.address;
    data['phone'] = this.phone;
    data['default_tax'] = this.defaultTax;
    data['available_for_delivery'] = this.availableForDelivery;

    data['has_media'] = this.hasMedia;
    data['has_favicon_media'] = this.hasFaviconMedia;
    data['rate'] = this.rate;
    data['reviews_count'] = this.reviewsCount;
    data['media'] = this.media;

    return data;
  }
}

